### ISSUE TITLE
Question about output of standalone vs online

### ISSUE THREAD

**Issue by bvaldebenitom** [mircare/Porter5#12]
Hi!

I've been doing some test with both the standalone version of Porter and the web version, and I'm looking into the differences of each output.

Web output: http://distilldeep.ucd.ie/~gianluca/distill_results/query160365365118818.html
Standalone output: https://github.com/mircare/Porter5/blob/master/example/2FLGA.ss8

Is there any way to convert the standalone output into something like the web output? What are the main differences between the two? 

Thanks in advance!

**Comment by mircare** [comment]
Hi @bvaldebenitom ,

The output of the standalone program is more informative than the web version one. It includes the confidence that Porter 5 assigns to each class. For example, the first few lines of the example at https://github.com/mircare/Porter5/blob/master/example/2FLGA.ss8 are:
```
#	AA	SS	G	H	I	E	B	C	S	T
1	N	C	0.0001	0.0001	0.0001	0.0001	0.0001	0.9995	0.0002	0.0002
2	I	C	0.0742	0.0147	0.0001	0.035	0.014	0.7952	0.0011	0.0658
3	S	C	0.108	0.0157	0.0001	0.0809	0.0142	0.513	0.142	0.1261
4	Q	C	0.1053	0.0257	0.0001	0.1762	0.0059	0.2696	0.234	0.1832
```

This means that Porter 5 is confident at 26.96% and 23.4% that the fourth AA is a _C_ or a _S_, respectively. This corresponds to a _2_ (= low confidence) in the web output. Please feel free to push a commit if you implement a simple script to convert the 2 formats.

**Comment by bvaldebenitom** [comment]
Thanks for the quick response @mircare . Will work on that simple script, and push a commit!
