### ISSUE TITLE
Porter5 "Killed" issue

### ISSUE THREAD

**Issue by sgorman90** [mircare/Porter5#13]
Hi All,

First off, my system runs Pop!_OS linux with 16 gb memory and a Ryzen 5 5600x 6 core processor. I run Porter5 in parallel on multiple sequences with CPU set to 3 and parallel set to 2, though I still have the below issue with other settings.

Usually on the first test run I have no issues, but after a couple of test runs on a particular class of proteins I get the following error in the log file:

- 13:39:28.388 INFO: Search results will be written to test011_TCF3_ZNF384.hhr

- 13:39:29.524 INFO: Searching 8290206 column state sequences.

- 13:39:29.552 INFO: test011_TCF3_ZNF384.fasta is in A2M, A3M or FASTA format

- 13:39:29.553 INFO: Iteration 1

- 13:39:29.853 INFO: Prefiltering database

- 13:41:21.032 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 556889

- 13:41:28.048 WARNING: database contains sequences that exceeds maximum allowed size (maxres = 20001). Maxres can be increased with parameter -maxres.

- 13:41:28.153 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 99165

- 13:41:28.153 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 99165

- 13:41:28.153 INFO: Scoring 99165 HMMs using HMM-HMM Viterbi alignment

- 13:41:28.180 INFO: Alternative alignment: 0

- 13:41:28.512 INFO: 2000 alignments done

- 13:41:28.958 INFO: 4000 alignments done

- 13:41:29.513 INFO: 6000 alignments done

- 13:41:30.172 INFO: 8000 alignments done

- 13:41:30.940 INFO: 10000 alignments done

- 13:41:31.826 INFO: 12000 alignments done

- 13:41:32.833 INFO: 14000 alignments done

- 13:41:33.956 INFO: 16000 alignments done

- 13:41:35.187 INFO: 18000 alignments done

- 13:41:36.559 INFO: 20000 alignments done

- 13:41:38.078 INFO: 22000 alignments done

- 13:41:39.746 INFO: 24000 alignments done

- 13:41:41.591 INFO: 26000 alignments done

- 13:41:43.606 INFO: 28000 alignments done

- 13:41:45.820 INFO: 30000 alignments done

- 13:41:48.245 INFO: 32000 alignments done

- 13:41:50.946 INFO: 34000 alignments done

- 13:41:53.940 INFO: 36000 alignments done

- 13:41:57.304 INFO: 38000 alignments done

- 13:42:01.173 INFO: 40000 alignments done

- 13:42:05.471 INFO: 42000 alignments done

- 13:42:09.795 INFO: 44000 alignments done

- 13:42:12.701 INFO: 46000 alignments done

- 13:42:14.711 INFO: 48000 alignments done

- 13:42:16.676 INFO: 50000 alignments done

- 13:42:18.732 INFO: 52000 alignments done

- 13:42:20.696 INFO: 54000 alignments done

- 13:42:20.699 WARNING: Number of match columns too large. Only first 19999 match columns will be kept!

- 13:42:20.704 WARNING: Number of match columns too large. Only first 19999 match columns will be kept!

- 13:42:22.779 INFO: 56000 alignments done

- 13:42:22.783 WARNING: Number of match columns too large. Only first 19999 match columns will be kept!

- 13:42:24.820 INFO: 58000 alignments done

- 13:42:26.784 INFO: 60000 alignments done

- 13:42:28.723 INFO: 62000 alignments done

- 13:42:30.772 INFO: 64000 alignments done

- 13:42:32.774 INFO: 66000 alignments done

- 13:42:34.843 INFO: 68000 alignments done

- 13:42:36.799 INFO: 70000 alignments done

- 13:42:38.719 INFO: 72000 alignments done

- 13:42:40.700 INFO: 74000 alignments done

- 13:42:42.624 INFO: 76000 alignments done

- 13:42:44.604 INFO: 78000 alignments done

- 13:42:46.505 INFO: 80000 alignments done

- 13:42:48.453 INFO: 82000 alignments done

- 13:42:50.438 INFO: 84000 alignments done

- 13:42:52.390 INFO: 86000 alignments done

- 13:42:54.348 INFO: 88000 alignments done

- 13:42:56.306 INFO: 90000 alignments done

- 13:42:58.295 INFO: 92000 alignments done

- 13:42:58.297 INFO: Stop after DB-HHM: 92000 because early stop  18.7068 < filter cutoff 20

- 13:42:58.300 INFO: Alternative alignment: 1

- 13:42:58.303 WARNING: Number of match columns too large. Only first 19999 match columns will be kept!

- 13:42:58.308 WARNING: Number of match columns too large. Only first 19999 match columns will be kept!

- 13:42:58.313 WARNING: Number of match columns too large. Only first 19999 match columns will be kept!

- 13:44:28.849 INFO: 87853 alignments done

- 13:44:28.985 INFO: Alternative alignment: 2

- 13:44:28.988 WARNING: Number of match columns too large. Only first 19999 match columns will be kept!

- 13:44:28.993 WARNING: Number of match columns too large. Only first 19999 match columns will be kept!

- 13:44:28.000 WARNING: Number of match columns too large. Only first 19999 match columns will be kept!

- 13:45:41.853 INFO: 61705 alignments done

- 13:45:41.914 INFO: Alternative alignment: 3

- 13:45:41.917 WARNING: Number of match columns too large. Only first 19999 match columns will be kept!

- 13:45:41.921 WARNING: Number of match columns too large. Only first 19999 match columns will be kept!

- 13:45:41.927 WARNING: Number of match columns too large. Only first 19999 match columns will be kept!

- 13:46:41.174 INFO: 47257 alignments done

Killed

Any help would be appreciated, and I can provide an example FASTA if need be to reproduce the error! 
Thanks!
Scott

**Comment by mircare** [comment]
Hi @sgorman90 , I would recommend you to check whether you can run hhblits on the FASTA leading to this issue. This type of error is typically linked to memory problems with HHblits, e.g. https://github.com/soedinglab/hh-suite/issues/102.

**Comment by sgorman90** [comment]
Thank you very much! You were correct, memory issues the culprit. I reduced the number of CPUs to bottleneck the process and that solved my issue.


Scott D. Gorman, Ph.D.

Postdoctoral Research Associate | Co-Department Rep | Structural Biology Department

St. Jude Children’s Research Hospital

o: 901-595-6136 | c: 617-842-0947 | Kriwacki Lab<http://www.stjuderesearch.org/kriwacki>

________________________________
