### ISSUE TITLE
Executing Predict file

### ISSUE THREAD

**Issue by vinhbiochem** [mircare/Porter5#2]
Hello! Would there happen to be a Predict file that would be compatible with MacOS systems? Any advice/recommendations would be appreciated.

**Comment by mircare** [comment]
Hi @vinhbiochem, Porter5 should work on a MacOS too. Have you copied the files to a different machine? Try adding the --setup parameter when running it or please be a bit more specific on the problem you encounter.

**Comment by vinhbiochem** [comment]
Hi @mircare ,

This is the following output I get after HHblits finishes its run:

HHblits executed in 245.63s
Alignments encoded in 0.65s
sh: /Users/labadmin/Porter5/scripts/Predict_BRNN/Predict: cannot execute binary file
Prediction in 3 classes made in 0.02s
Traceback (most recent call last):
  File "/Users/labadmin/Porter5/Porter5.py", line 120, in <module>
    prob_hh = list(map(float, open(pid+".flatpsi.ann.probsF", "r").readlines()[3].split()))
FileNotFoundError: [Errno 2] No such file or directory: 'PorterTest.fa.flatpsi.ann.probsF'

I have tried running the Predict file alone but receive the same 'cannot execute binary file' output. Please let me know if I am just totally doing something wrong.

**Comment by mircare** [comment]
It looks like the Predict file is somehow corrupted or not executable.
You can check the permissions with:
`ls -l /Users/labadmin/Porter5/scripts/Predict_BRNN/Predict`
You can give execute permission with:
`chmod a+x /Users/labadmin/Porter5/scripts/Predict_BRNN/Predict`

If that does not help, you can recompile the Predict with:
`cd /Users/labadmin/Porter5/scripts/Predict_BRNN/Predict`
`make`

**Comment by vinhbiochem** [comment]
Hi @mircare ,

Thank you! The recompilation worked and I am able to run Predict. The script can work to completion, but I am having a bit of trouble as I don't believe Predict is providing correct values.

I have ran the sequence being tested on your server, and have gotten different results (sequence should contain helices, sheets, and coils, not just helix). I'm not sure if the probs files are being written out correctly, and was wondering if you had any recommendations for how to troubleshoot this. I'm attaching several output files (converted to text) I think might better explain my situation, please let me know if you need anything else.

[PorterTest.fa.flatpsi.txt](https://github.com/mircare/Porter5/files/2780651/PorterTest.fa.flatpsi.txt)
[PorterTest.fa.flatpsi.ann.txt](https://github.com/mircare/Porter5/files/2780652/PorterTest.fa.flatpsi.ann.txt)
[PorterTest.fa.flatpsi.ann.probs.txt](https://github.com/mircare/Porter5/files/2780653/PorterTest.fa.flatpsi.ann.probs.txt)
[PorterTest.fa.flatpsi.ann+ss3.txt](https://github.com/mircare/Porter5/files/2780654/PorterTest.fa.flatpsi.ann%2Bss3.txt)
[PorterTest.fa.flatpsi.ann+ss3.probs.txt](https://github.com/mircare/Porter5/files/2780655/PorterTest.fa.flatpsi.ann%2Bss3.probs.txt)
[PorterTest.fa.psi.txt](https://github.com/mircare/Porter5/files/2780656/PorterTest.fa.psi.txt)
[PorterTest.fa.ss3.txt](https://github.com/mircare/Porter5/files/2780657/PorterTest.fa.ss3.txt)
[PorterTest.fa.ss8.txt](https://github.com/mircare/Porter5/files/2780658/PorterTest.fa.ss8.txt)

**Comment by mircare** [comment]
Hi @vinhbiochem, 
Thank you for reporting your problem.
The issue is not the Predict but the extension expected.
Just git pull to get my fix and use any extension you find convenient:
`cd /Users/labadmin/Porter5/`
`git pull`

**Comment by vinhbiochem** [comment]
Hi @mircare,

Forgive me but just making sure we're on the same page, in the folders, I have not changed any of the files to a .txt extension (only changed here so that I am able to upload the files to GitHub). I'm still having the same troubles with Porter5 reporting my entire sequence as helix. Would there be any files I would send to you that might help troubleshoot this?

**Comment by mircare** [comment]
Please send me the output of the following command:
`cat /Users/labadmin/Porter5/scripts/Predict_BRNN/models/modelv8_ss3`

**Comment by vinhbiochem** [comment]
I get the following:

odelv8_ss3
3
models/SS3/trained-0.model25Fv8
models/SS3/trained-0.model30Ffatv8
models/SS3/trained-0.model30Fv8

**Comment by mircare** [comment]
That does not look good. Please try the following:
`cd /Users/labadmin/Porter5/scripts/Predict_BRNN/`
`bash set_models.sh`

If nothing changes, then send me again:
` cat /Users/labadmin/Porter5/scripts/Predict_BRNN/models/modelv8_ss3`

**Comment by mircare** [comment]
All right, sed seems to be the problem (you can read more here: https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux).

Please try to git pull again and let me know.

**Comment by vinhbiochem** [comment]
Everything works now! Thank you @mircare for all of your help. This program makes the most accurate ss predictions I have seen and will really help me out with my research. Thank you again!
