### ISSUE TITLE
Process-Alignment Error

### ISSUE THREAD

**Issue by vinhbiochem** [mircare/Porter5#3]
Hello! I'm not entirely sure why, but Porter5 was working for the past few runs I was doing with the --flag. However, when I remove the flag to include psiblast, I began encountering troubles that resurfaced when I returned back to the --fast flag. I was wondering if you could help me out.

After originally running,
~/Porter5/Porter5.py -i PorterTest.fa --fast

I get the following message after the hhblits alignment: 
sed: -i: No such file or directory
HHblits executed in 387.83s
sh: python3: command not found
Traceback (most recent call last):
  File "/Users/labadmin/Porter5/Porter5.py", line 76, in <module>
    flatpsi_ann = open(filename+".flatpsi.ann", "r").readlines()
IOError: [Errno 2] No such file or directory: 'PorterTest.fa.flatpsi.ann'

I recognize that the .ann file is created by Process-Alignment, so from there I tried running that script alone.
STK-CHEM-Q1F8J8:PTestOutput labadmin$ python /Users/labadmin/Porter5/scripts/process-alignment.py PorterTest.fa.flatpsi flatpsi 1
Traceback (most recent call last):
  File "/Users/labadmin/Porter5/scripts/process-alignment.py", line 94, in <module>
    weights[i] = weights[i] - math.log(frequencies[j][aa[lines[i+1][j]]])
ValueError: math domain error

Would this happen to still be a problem with the sed -i flag discussed in the earlier issue? Please let me know if any files/outputs should be submitted.

**Comment by vinhbiochem** [comment]
Oh I should note that I changed the 'ProcessAlignment.py" script at one point. HHBlits recognizes gaps with a '-' rather than a '.', so I replaced that in the aa dictionary in line 22.

**Comment by vinhbiochem** [comment]
Hi @mircare, 

No problem! Thank you for the fast fixes!

After pulling, and reverting to the aa dictionary that included '.', I ran the command and ended up with the following:

STK-CHEM-Q1F8J8:PTestOutput labadmin$ python ~/Porter5/Porter5.py -i PorterTest.fa --fast --cpu 4
~~~~~~~~~ Prediction of PorterTest.fa started ~~~~~~~~~
HHblits executed in 126.09s
sh: python3: command not found
Traceback (most recent call last):
  File "/Users/labadmin/Porter5/Porter5.py", line 76, in <module>
    flatpsi_ann = open(filename+".flatpsi.ann", "r").readlines()
IOError: [Errno 2] No such file or directory: 'PorterTest.fa.flatpsi.ann'

I looked into the directory and noticed that this script created 'PorterTest.fa.flatpsi-e' files. Perhaps the sed command created incorrect files that aren't being read?

**Comment by mircare** [comment]
Yes, that's probably the case but I don't have a Mac to double check at the moment.
Please git pull (without modifying the aa dictionary) and let me know.

If you have any more problem, please attach the PorterTest.fa.flatpsi file.
Otherwise, you can also try to make this work: https://github.com/mircare/Porter5/blob/master/scripts/process-psi.sh

**Comment by vinhbiochem** [comment]
Just git pulled and ran the script. We're hitting the same error but I think it might have something more related to the value error aforementioned. I'm attaching the flatpsi file along with the flatpsi-e file created (converted to txt for uploading). Please let me know if there's anything else you would need!

[PorterTest.fa.flatpsi-e.txt](https://github.com/mircare/Porter5/files/2784938/PorterTest.fa.flatpsi-e.txt)
[PorterTest.fa.txt](https://github.com/mircare/Porter5/files/2784939/PorterTest.fa.txt)

**Comment by mircare** [comment]
Porter5 expects a single sequence in fasta format as input. 
Did you use PorterTest.fa.txt - which is a psi file - instead?

**Comment by vinhbiochem** [comment]
Forgive me, that file is supposed to be PorterTest.fa.flatpsi, .flatpsi was removed when I switched it to text format for uploading. I'm using a fasta format file for my sequence.

**Comment by mircare** [comment]
That's interesting. So you have two equal files with two different filenames: .fa.flatpsi-e and .fa.flatpsi.
Try the following:
`python3 ~/Porter5/scripts/process-alignment.py  PorterTest.fa.flatpsi flatpsi`

Also, are you using python3, e.g. python3 ~/Porter5/Porter5.py -i PorterTest.fa --fast --cpu 4?

**Comment by vinhbiochem** [comment]
Forgive me for the late response. For some reason my computer's python PATH went straight to 2.7 even though I installed 3.6 After fixing this the code worked clean with no errors (both on --fast and without). Thank you again for all the help, I really appreciate it.

**Comment by mircare** [comment]
I have just added a warning for that, you can git pull if you want to be sure that you're using python3. 
All the best with your research and thank you for making Porter5 compatible with MacOS!
