### ISSUE TITLE
No such file or directory: 'Porter5/example/2FLGA.fasta.flatpsi.an

### ISSUE THREAD

**Issue by katrinr** [mircare/Porter5#4]
Hi,
I would love to use Porter5, but I have some problems with the initial steps, which seems to be addressed in one or the other previous issues, however testing the path to the databases did not help, so I guess my paths are somehow not fully correct. Here is my config.ini

```
[DEFAULT]                                                                                                                               
psiblast = <path_to_packages>/packages/databases/psi-blast/ncbi-blast-2.8.1+                                                                
uniref90 = <path_to_packages>/packages/databases/uniref90                                                                                   
hhblits = <path_to_packages>/packages/hh-suite                                                                                              
uniprot20 = <path_to_packages>/packages/databases/uniprot20_2016_02
```
How should it look like?
Thanks in advance

**Comment by katrinr** [comment]
Figured it out, maybe useful for others, so I post it here

[DEFAULT]                                                                                                                               
psiblast = <path_to_packages>/packages/databases/psi-blast/ncbi-blast-2.8.1+                                                                
uniref90 = <path_to_packages>/packages/databases/uniref90/uniref90.fasta                                                                    
hhblits = <path_to_packages>/packages/hh-suite/build/bin/hhblits                                                                            
uniprot20 = <path_to_packages>/packages/databases/uniprot20_2016_02/uniprot20_2016_02 

Btw thanks for the tool!

**Comment by DRL36** [comment]
I encountered the same issue here and I've tried changing the default, but it still went wrong. Any ideas on how to fix this?

**Comment by mircare** [comment]
@DRL36 Please try the below command and open another issue with more details if the problem persists.

`python3 Porter5.py -i example/2FLGA.fasta --cpu 4 --setup`
