### ISSUE TITLE
Errors during setup and prediction

### ISSUE THREAD

**Issue by beginnercn** [mircare/Porter5#5]
below is the complete log, any suggestion to fix it? 

$ python3 /Users/username/Porter5/Porter5.py -i /Users/username/Porter5/example/2FLGA.fasta --cpu 4 --fast
Please insert the absolute path to psiblast (e.g., /home/username/psiblast): 
Please insert the absolute path to uniref90 (e.g., /home/username/UniProt/uniref90.fasta): 
Please insert the call to HHblits (e.g., hhblits): /Users/username/hh-suite/build/bin/hhblits 
Please insert the absolute path to uniprot20 - DATABASE NAME INCLUDED (e.g., /home/username/uniprot20_2016_02/uniprot20_2016_02): /Users/username/Databases/uniprot20_2016_02/uniprot20_2016_02            
g++ -c -O3 Layer.cxx
Layer.cxx:11:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make: *** [Layer.o] Error 1

>>>>> Setup completed successfully. If you encounter any problems in future, please run "python3 Porter5.py --setup". <<<<<

~~~~~~~~~ Prediction of /Users/username/Porter5/example/2FLGA.fasta started ~~~~~~~~~
HHblits executed in 39.15s
Alignments encoded in 0.13s
sh: /Users/username/Porter5/scripts/Predict_BRNN/Predict: Permission denied
Prediction in 3 classes made in 0.00s
Traceback (most recent call last):
  File "/Users/username/Porter5/Porter5.py", line 120, in <module>
    prob_hh = list(map(float, open(filename+".flatpsi.ann.probsF", "r").readlines()[3].split()))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/username/Porter5/example/2FLGA.fasta.flatpsi.ann.probsF'

**Comment by mircare** [comment]
The issue is with the OMP library so I have just commented it out. Please get the latest version of Porter5 and let me know if that works.
`cd /Users/username/Porter5/`
`git pull`

**Comment by beginnercn** [comment]
Thank you mircare! it works! I believe Porter5 will be very helpful for our research.

**Comment by beginnercn** [comment]
There's one more question. while the web server provides confidence values for the prediction, this standalone Porter5 do not create such values in the result data. Is there something missing ? Thanks in advance.

**Comment by mircare** [comment]
As you can see [here](https://github.com/mircare/Porter5/blob/master/example/2FLGA.ss3), the standalone creates a column per class - _Helix_, _Sheet_ and _Coil_ for 3 state prediction - to report the respective confidence.

**Comment by IndigoMad** [comment]
Hi, mircare
I have the same error now:
sh: /Users/username/Porter5/scripts/Predict_BRNN/Predict: Permission denied
I do entered: git pull
but it return another error:
error: could not open .git/FETCH_HEAD：????
and I found that there is only a file named HEAD, but not  FETCH_HEAD ,in my .git folder

> The issue is with the OMP library so I have just commented it out. Please get the latest version of Porter5 and let me know if that works.
> `cd /Users/username/Porter5/`
> `git pull`
