### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'example/2FLGA.fasta.flatpsi.ann'

### ISSUE THREAD

**Issue by DRL36** [mircare/Porter5#7]
Thank you for the quick response!

I tried python3 Porter5.py -i example/2FLGA.fasta --cpu 4 --setup, the setup completed successfully while the FileNotFoundError still exists.

I think I encountered almost the same problem stated here: https://stackoverflow.com/questions/55283434/unable-to-run-porter5-generating-flatpsi-file-instead-of-psi

Here's my default setting:
    hhblits = '/home/username/hh-suite/build/bin/hhblits'
    uniprot20 = '/home/username/Downloads/uniprot20_2016_02'
I commented out psiblast and uniref90 since I was running the fast version. btw, I'm working on ubuntu 18.04.

Here are the error messages:
wc: Porter5/example/2FLGA.fasta.psi: No such file or directory
awk: cannot open Porter5/example/2FLGA.fasta.psi (No such file or directory)
HHblits executed in 0.02s
Traceback (most recent call last):
  File "/home/usr/Porter5/scripts/process-alignment.py", line 37, in <module>
    sequences = lines[0] = len(lines) - 1
IndexError: list assignment index out of range
Traceback (most recent call last):
  File "Porter5/Porter5.py", line 86, in <module>
    flatpsi_ann = open(filename+".flatpsi.ann", "r").readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'Porter5/example/2FLGA.fasta.flatpsi.ann'

**Comment by mircare** [comment]
Please change the second line of your config file as follow:
> uniprot20 = '/home/username/Downloads/uniprot20_2016_02/uniprot20_2016_02 '

Thank you for letting me know about the question on Stackoverflow.

**Comment by DRL36** [comment]
> Please change the second line of your config file as follow:
> 
> > uniprot20 = '/home/username/Downloads/uniprot20_2016_02/uniprot20_2016_02 '
> 
> Thank you for letting me know about the question on Stackoverflow.

Thank you! But I think changing wouldn't help because I unzipped it into one single folder. But would give it a try.

**Comment by Dreycey** [comment]
This was super helpful!!
