### ISSUE TITLE
wc: Porter5/example/2FLGA.fasta.psi: No such file or directory

### ISSUE THREAD

**Issue by papnikol** [mircare/Porter5#8]
I get the following error:

```
> python3 Porter5/Porter5.py -i Porter5/example/2FLGA.fasta --cpu 4 --fast
> ~~~~~~~~~ Prediction of Porter5/example/2FLGA.fasta started ~~~~~~~~~
> wc: Porter5/example/2FLGA.fasta.psi: No such file or directory
> awk: fatal: cannot open file `Porter5/example/2FLGA.fasta.psi' for reading (No such file or directory)
> HHblits executed in 1.23s
> Traceback (most recent call last):
>   File "/mnt/data/software/Porter5/Porter5/scripts/process-alignment.py", line 37, in <module>
>     sequences = lines[0] = len(lines) - 1
> IndexError: list assignment index out of range
> Traceback (most recent call last):
>   File "Porter5/Porter5.py", line 82, in <module>
>     flatpsi_ann = open(filename+".flatpsi.ann", "r").readlines()
> FileNotFoundError: [Errno 2] No such file or directory: 'Porter5/example/2FLGA.fasta.flatpsi.ann'
```

I know it has been mentioned in 2 other issues but the respective solutions did not help me.

- This is my configuration file:

```
[DEFAULT]
psiblast = /mnt/data/software/Porter5/blast/ncbi-blast-2.10.1+/bin/psiblast
uniref90 = /mnt/data/software/Porter5/uniref90/uniref90.fasta
hhblits = /usr/bin/hhblits
uniprot20 = /mnt/data/software/Porter5/uniprot20/uniprot20_2016_02/uniprot20_2016_02
```

- There is only the intermediary file _2FLGA.fasta.flatpsi_

- contents of 2FLGA.fasta.log (I checked uniprot20_2016_02_cs219.ffindex, it is not empty and does not seem corrupted):

```
- 20:47:21.837 INFO: Search results will be written to Porter5/example/2FLGA.hhr

ffindex.c:452 ffindex_index_parse: mlock: Cannot allocate memory
- 20:47:22.228 WARNING: In /build/hhsuite-rhvmkl/hhsuite-3.0~beta2+dfsg/src/hhdatabase.cpp:50: FFindexDatabase:

- 20:47:22.228 WARNING:         Could not read index file/mnt/data/software/Porter5/uniprot20/uniprot20_2016_02/uniprot20_2016_02_cs219.ffindex. Is the file empty or corrupted?

ffindex.c:452 ffindex_index_parse: mlock: Cannot allocate memory
- 20:47:22.657 WARNING: In /build/hhsuite-rhvmkl/hhsuite-3.0~beta2+dfsg/src/hhdatabase.cpp:50: FFindexDatabase:

- 20:47:22.657 WARNING:         Could not read index file/mnt/data/software/Porter5/uniprot20/uniprot20_2016_02/uniprot20_2016_02_a3m.ffindex. Is the file empty or corrupted?
```

**Comment by mircare** [comment]
Looks like something is wrong with your HHblits database. Try editing the last line of your configuration file as follow:
`uniprot20 = /mnt/data/software/Porter5/uniprot20/uniprot20_2016_02`

If that doesn't solve it, please let me know the output of the following command:
`uniprot20 = /mnt/data/software/Porter5/uniprot20/uniprot20_2016_02`

**Comment by papnikol** [comment]
Thanks for your prompt response
> Looks like something is wrong with your HHblits database. Try editing the last line of your configuration file as follow:
> `uniprot20 = /mnt/data/software/Porter5/uniprot20/uniprot20_2016_02`

I had alreasdy tried it, it did not work (all files are located in /mnt/data/software/Porter5/uniprot20/uniprot20_2016_02 so I think the way I already have it is OK anyways).
```
$ ll /mnt/data/software/Porter5/uniprot20/uniprot20_2016_02
md5sum   
uniprot20_2016_02.cs219
uniprot20_2016_02_hhm_db.index
uniprot20_2016_02_a3m_db
uniprot20_2016_02_cs219.ffdata
uniprot20_2016_02_hhm.ffdata
uniprot20_2016_02_a3m_db.index
uniprot20_2016_02_cs219.ffindex
uniprot20_2016_02_hhm.ffindex
uniprot20_2016_02_a3m.ffdata
uniprot20_2016_02.cs219.sizes
uniprot20_2016_02_a3m.ffindex
uniprot20_2016_02_hhm_db
```


> If that doesn't solve it, please let me know the output of the following command:
> `uniprot20 = /mnt/data/software/Porter5/uniprot20/uniprot20_2016_02`

I think you repasted your previous paste instead of the command :)

**Comment by mircare** [comment]
My bad, try the following from the command line:
`hhblits -d /mnt/data/software/Porter5/uniprot20/uniprot20_2016_02 -i test.fasta -opsi test.psi -n 1 -maxfilt 150000 -maxmem 27 -v 2`

Make sure to point to a fasta file instead of **test.fasta**, e.g. _Porter5/example/2FLGA.fasta_.

**Comment by papnikol** [comment]
> 
> 
> My bad, try the following from the command line:
> `hhblits -d /mnt/data/software/Porter5/uniprot20/uniprot20_2016_02 -i test.fasta -opsi test.psi -n 1 -maxfilt 150000 -maxmem 27 -v 2`
> 
> Make sure to point to a fasta file instead of **test.fasta**, e.g. _Porter5/example/2FLGA.fasta_.

Thanks a lot, the command did not work so I tried removing and reinstalling hhsuite and that fixed it. I had  installed it using apt but removing it and **manually installing it from github** did the job. 

I appreciate your help and the time you spent.
