### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'query/2FLGA.fasta.flatpsi.ann'

### ISSUE THREAD

**Issue by suppakoko** [mircare/Porter5#9]
I have a question

I pulled the mircare/porter5 image from the docker hub
and set the config.ini like below

[DEFAULT]
psiblast = psiblast
uniref90 = /uniref90/uniref90.fasta
hhblits = hhblits
uniprot20 = /uniprot20/uniprot20_2016_20/uniprot20_2016_20

and then insert the command below
python3 Porter5.py -i query/2FLGA.fasta --cpu 4 --setup

~~~~~~~~~ Prediction of query/2FLGA.fasta started ~~~~~~~~~
PSI-BLAST executed in 1302.09s
wc: query/2FLGA.fasta.psi: No such file or directory
awk: cannot open query/2FLGA.fasta.psi (No such file or directory)
HHblits executed in 0.07s
Traceback (most recent call last):
  File "/Porter5/scripts/process-alignment.py", line 37, in <module>
    sequences = lines[0] = len(lines) - 1
IndexError: list assignment index out of range
Traceback (most recent call last):
  File "Porter5.py", line 82, in <module>
    flatpsi_ann = open(filename+".flatpsi.ann", "r").readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'query/2FLGA.fasta.flatpsi.ann'

I don't know why this error happened?

Anybody can help me?

**Comment by mircare** [comment]
Hi @suppakoko, not sure why you have **--setup** in your command. Did you follow the instructions at https://github.com/mircare/Porter5#use-the-docker-image?

**Comment by suppakoko** [comment]
Thank you for your kind answer
I already try --setup options but it also doesn't work
so i just install porter5 and other requirement programs. and then it work.
thanks~

2020년 8월 4일 (화) 오전 5:56, Mirko Torrisi <notifications@github.com>님이 작성:
